/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { DataStore, DataStoreInterface } from "../DataStore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "_store",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value_",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a7806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806320965255146100465780635524107714610064578063defbed8014610080575b600080fd5b61004e6100b0565b60405161005b919061016d565b60405180910390f35b61007e600480360381019061007991906101b9565b6100f6565b005b61009a60048036038101906100959190610244565b61013c565b6040516100a7919061016d565b60405180910390f35b60008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905090565b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555050565b60006020528060005260406000206000915090505481565b6000819050919050565b61016781610154565b82525050565b6000602082019050610182600083018461015e565b92915050565b600080fd5b61019681610154565b81146101a157600080fd5b50565b6000813590506101b38161018d565b92915050565b6000602082840312156101cf576101ce610188565b5b60006101dd848285016101a4565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610211826101e6565b9050919050565b61022181610206565b811461022c57600080fd5b50565b60008135905061023e81610218565b92915050565b60006020828403121561025a57610259610188565b5b60006102688482850161022f565b9150509291505056fea2646970667358221220529832afaab283dc4bf0f7b5d76b2f5733a17886257758c99c9fbcf1a11f4a6164736f6c63430008180033";

type DataStoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DataStoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DataStore__factory extends ContractFactory {
  constructor(...args: DataStoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DataStore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DataStore__factory {
    return super.connect(runner) as DataStore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DataStoreInterface {
    return new Interface(_abi) as DataStoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DataStore {
    return new Contract(address, _abi, runner) as unknown as DataStore;
  }
}
