/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataStore } from "./DataStore";
export * as factories from "./factories";
export { DataStore__factory } from "./factories/DataStore__factory";
